"""
PDF Report Renderer: WeasyPrint implementation.

This module uses WeasyPrint to convert the HTML report (generated by Jinja2)
into a professional PDF document.
"""

from pathlib import Path
from typing import Any

from weasyprint import HTML, CSS
from domain.report_schema import ReportJSON
from renderer.html_report import render_html_report, TEMPLATE_DIR


def render_pdf_report(
    report_json: ReportJSON,
    narrative: str | None = None
) -> bytes:
    """
    Render ReportJSON to PDF bytes.
    
    Args:
        report_json: The structured report data
        narrative: Optional narrative text
        
    Returns:
        PDF file bytes
    """
    # 1. Generate HTML
    html_content = render_html_report(report_json, narrative)
    
    # 2. Convert to PDF
    # Base URL is set to template dir so relative assets (if added later) work
    return HTML(string=html_content, base_url=str(TEMPLATE_DIR)).write_pdf()


def save_pdf_report(
    report_json: ReportJSON,
    output_path: str | Path,
    narrative: str | None = None
) -> Path:
    """
    Render and save PDF report to file.
    
    Args:
        report_json: The structured report data
        output_path: Path to save the PDF file
        narrative: Optional narrative text
        
    Returns:
        Path to the saved file
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    pdf_bytes = render_pdf_report(report_json, narrative)
    output_path.write_bytes(pdf_bytes)
    
    return output_path


class PDFReportGenerator:
    """
    Generator class for PDF CMA reports.
    """
    
    def __init__(self, **kwargs: Any):
        """Initialize PDF generator."""
        # Config options can be added here
        pass
    
    def render(self, report_json: ReportJSON, narrative: str | None = None) -> bytes:
        """Render to PDF bytes."""
        return render_pdf_report(report_json, narrative)
    
    def save(self, report_json: ReportJSON, output_path: str | Path, narrative: str | None = None) -> Path:
        """Save to PDF file."""
        return save_pdf_report(report_json, output_path, narrative)
